### create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "johndoe419@gmail.com",
    "password": "Password"
}


### signIn existing user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "johndoe419@gmail.com",
    "password": "Password"
}
